version: "2"

services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - backend

  smtp:
    image: reachfive/fake-smtp-server
    networks:
      - backend
    ports:
      - 1080:1080

  catapulte:
    image: jdrouet/catapulte:master
    environment:
      RUST_LOG: info
      SMTP_HOSTNAME: smtp
      SMTP_PORT: 1025
      TEMPLATE_PROVIDER: jolimail
      TEMPLATE_PROVIDER_JOLIMAIL_BASE_URL: http://jolimail:3000
    depends_on:
      - jolimail
      - smtp
    networks:
      - backend
    ports:
      - 3010:3000

  jolimail:
    image: jdrouet/jolimail:master
    environment:
      DATABASE_HOST: database
      DATABASE_USER: postgres
      DATABASE_DBNAME: postgres
      EXAMPLE_CATAPULTE_BASE_URL: http://localhost:3010
      RUST_LOG: info
    networks:
      - backend
    ports:
      - 8080:3000
    depends_on:
      - database

networks:
  backend: {}
